ci: fix not working eslint action (#32)
* fix: ci: workflow error

* fix: ci: update eslint

* fix: ci: update eslint again

* ci: delete global pkg

* ci: update pkg

* ci: update eslint workflow

* ci: update eslint workflow again

* ci: fix commitlint

diff --git a/.github/workflows/eslint.yml b/.github/workflows/eslint.yml
--- a/.github/workflows/eslint.yml
+++ b/.github/workflows/eslint.yml
@@ -1,6 +1,5 @@
 name: ESLint
 
-# workflow is triggered on PRs to main
 on:
   pull_request:
     branches:
@@ -15,35 +14,31 @@ jobs:
       security-events: write
       actions: read
 
-    # sequential steps that make up this job
     steps:
-    
-      # checks out your repository code to the runner
       - name: Checkout code
         uses: actions/checkout@v4
 
-       # installs ESLint, ESLint stylistic plugin, and SARIF formatter on runner
       - name: Install ESLint
         run: |
-          npm install eslint@^9.0.0
-          npm install @stylistic/eslint-plugin@^4.2.0
-          npm install @microsoft/eslint-formatter-sarif@3.1.0
+          npm install eslint
+          npm install @stylistic/eslint-plugin
+          npm install @microsoft/eslint-formatter-sarif
 
-      # runs ESLint on runner, 
       - name: Run ESLint
         env:
           SARIF_ESLINT_IGNORE_SUPPRESSED: "true"
         run: |
-          npx eslint .\
-            --config eslint.config.js\
-            --ext .js,.jsx,.ts,.tsx\
-            --format @microsoft/eslint-formatter-sarif\
-            --output-file eslint-results.sarif
+          npx eslint . --config eslint.config.js --ext .js --format @microsoft/eslint-formatter-sarif --output-file eslint-results.sarif || echo "exit_code=$?" >> $GITHUB_OUTPUT
         continue-on-error: true
 
-      # sends results back to GitHub
       - name: Upload analysis results to GitHub
         uses: github/codeql-action/upload-sarif@v3
         with:
           sarif_file: eslint-results.sarif
           wait-for-processing: true
+
+      - name: Fail if ESLint had errors
+        if: steps.eslint.outputs.exit_code != ''
+        run: |
+          echo "❌ ESLint found errors!"
+          exit 1
